# [START django_app]
runtime: python310

entrypoint: gunicorn -b :$PORT dj_project.wsgi

env_variables:
  SECRET_KEY: 'django-insecure-7s3(w-q))9(#ca0e16^#f*0k7i)1gckcy!jg$c2h*0-f#j92cj' 
  USER_EMAIL: 'xxc199548@gmail.com'
  USER_DB: 'ranco'
  USER_PW: 'Hf201701!'

handlers:
# This configures Google App Engine to serve the files in the app's
# static directory.
- url: /static
  static_dir: static/
# This handler routes all requests not caught above to the main app. 
# It is required when static routes are defined, but can be omitted 
# (along with the entire handlers section) when there are no static 
# files defined.
- url: /.*
  script: auto
# [END django_app]