# Generated by Django 4.1.3 on 2022-12-03 08:39

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=pathlib.PurePosixPath('/home/rxu_admin/My_Websites/static/Default.jpg'), upload_to='profile_pics'),
        ),
    ]
