# Generated by Django 4.1.3 on 2022-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='profile_pics'),
        ),
    ]
