# Generated by Django 4.1.3 on 2024-08-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bucketlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
