# Generated by Django 4.1.3 on 2024-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerCustomer',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateField(null=True)),
                ('used', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=50000)),
            ],
        ),
    ]
