# Generated by Django 4.1.3 on 2024-08-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekercustomer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seekercustomer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seekercustomer',
            name='token',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
