# Generated by Django 4.1.3 on 2024-08-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_alter_seekercustomer_contact_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seekercustomer',
            index=models.Index(fields=['token'], name='customer_to_token_35f7fa_idx'),
        ),
        migrations.AlterModelTable(
            name='seekercustomer',
            table='customer_tokens',
        ),
    ]
