# Generated by Django 4.1.3 on 2024-08-29 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_seekercustomer_customer_to_token_35f7fa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekercustomer',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
